"""Search client — LLM-backed mock when no Tavily key is configured.

Returns plausible source documents generated by the LLM so the rest of the
pipeline can run end-to-end without a real search API.
"""

import json
import re

from multi_agent_research_lab.core.schemas import SourceDocument
from multi_agent_research_lab.services.llm_client import LLMClient

_SYSTEM = (
    "You are a search engine simulator. Given a research query, return a JSON array "
    "of search results. Each result must have: title (string), url (string, realistic HTTPS URL), "
    "snippet (string, 2-3 sentences summarising the content). "
    "Return ONLY valid JSON — no markdown fences, no extra text."
)


class SearchClient:
    """LLM-backed mock search. Swap in Tavily/SerpAPI for production."""

    def __init__(self, llm_client: LLMClient) -> None:
        self._llm = llm_client

    def search(self, query: str, max_results: int = 5) -> list[SourceDocument]:
        prompt = (
            f"Research query: {query}\n\n"
            f"Return exactly {max_results} search results as a JSON array."
        )
        response = self._llm.complete(_SYSTEM, prompt, max_tokens=1024)
        return self._parse(response.content, max_results)

    def _parse(self, raw: str, max_results: int) -> list[SourceDocument]:
        # Strip any accidental markdown fences
        cleaned = re.sub(r"```(?:json)?|```", "", raw).strip()
        try:
            items = json.loads(cleaned)
            if not isinstance(items, list):
                items = [items]
        except json.JSONDecodeError:
            return []
        docs: list[SourceDocument] = []
        for item in items[:max_results]:
            if isinstance(item, dict):
                docs.append(SourceDocument(
                    title=item.get("title", "Unknown"),
                    url=item.get("url"),
                    snippet=item.get("snippet", ""),
                ))
        return docs
